# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1

orbs:

  telegram: jcminarro/telegram@dev:alpha

jobs:

  build:

    working_directory: ~/RetroMusicPlayer

    docker:
      - image: circleci/android:api-28

    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx2400m

    steps:
      - checkout

      - restore_cache:
          keys:
            - retro-dependencies-{{ checksum "build.gradle" }}
            - retro-dependencies-

      - run:
          name: Assemble
          command: ./gradlew assembleNormalDebug
      - run:
          name: Assemble
          command: ./gradlew clean assembleNormalRelease

      - run:
          name: Sign
          command: java -jar sign.jar app/build/outputs/apk/normal/release/app-normal-release-unsigned.apk --override
          
      - telegram/notify:
          message: "Uploading new version, Well the apk is signed even though the name states otherwise"

      - telegram/sendfile:
          file-path: app/build/outputs/apk/normal/release/app-normal-release-unsigned.apk

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - save_cache:
          paths:
            - ~/.gradle
          key: retro-dependencies-{{ checksum "build.gradle" }}
