# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    branches:
      ignore:
        - master
        
    working_directory: ~/RetroMusicPlayer

    docker:
      - image: circleci/android:api-29

    steps:
      - checkout
      
      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assembleNormalDebug
          
      - run:
          name: Assemble
          command: ./gradlew assembleNormalRelease

      - run:
          name: Sign
          command: java -jar sign.jar app/build/outputs/apk/normal/release/RetroPlayer-release.apk --override

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

          
      - store_artifacts:
          path: app/build/reports
          destination: reports

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper