# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1

jobs:

  build:

    working_directory: ~/RetroMusicPlayer

    docker:
      - image: cimg/android:2022.09

    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx2400m

    steps:
      - checkout

      - restore_cache:
          keys:
            - retro-dependencies-{{ checksum "build.gradle" }}
            - retro-dependencies-

      - run:
          name: Assemble
          command: ./gradlew assembleDebug
      - run:
          name: Assemble
          command: ./gradlew --no-daemon clean assembleNormalRelease

      - run:
          name: Sign
          command: java -jar sign.jar app/build/outputs/apk/normal/release/RetroPlayer-release.apk --override

      - run:
          name: Upload to Telegram
          command: |
            curl -F caption="" -F document=@app/build/outputs/apk/normal/release/RetroPlayer-release.apk "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument?chat_id=${TELEGRAM_CHAT_ID}"

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - save_cache:
          paths:
            - ~/.gradle
          key: retro-dependencies-{{ checksum "build.gradle" }}
          
    resource_class: large
